import ThemeProvider, { GlobalStyle } from "@/styles/global";
import StyledComponentsRegistry from "@/styles/registry";
import Image from "next/image";

import logoImg from "../assets/logo.svg";
import * as S from "./styles";

export const metadata = {
  title: {
    default: "Home | Ignite Shop",
    template: "%s | Ignite Shop",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider>
            <S.Container>
              <S.Header>
                <Image src={logoImg} alt="" />
              </S.Header>

              {children}
            </S.Container>
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
