export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Template({ children }: { children: React.ReactNode }) {
  return (
    <>
      {/* <p>Recarrega toda vez, bom pra reiniciar componentes</p> */}
      {children}
    </>
  );
}
